import localFont from "next/font/local";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { ThemeProvider } from "next-themes";

const vaz = localFont({
  src: "../app/fonts/Vazir-FD.woff2",
  display: "swap",

});
export const metadata = {
  title: "فرم نظرسنجی",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa-IR" dir="rtl" suppressHydrationWarning>
      <body
        className={`h-screen w-screen  dynamic-padding test overflow-auto 
           bg-gray-600 text-blue-500
           text-small
            xl:text-amber-300 xl:text-xl 
             2xl:text-purple-500 2xl:text-7xl 
             md:text-xl
              md:text-red-600
               ${vaz.className} antialiased`}
      >
        <ThemeProvider  >
      <NextUIProvider 
      theme={{
        extend: {
          colors: {
            primary: "#ff007a", // رنگ اصلی
            secondary: "#f5a623", // رنگ ثانویه
            gradient: "linear-gradient(112deg, #ff007a -25%, #f5a623 100%)", // گرادینت
            textPrimary: "#333333", // رنگ متن اصلی
            textSecondary: "#888888", // رنگ متن ثانویه
          },
        },
      }}>  {children} </NextUIProvider>

        </ThemeProvider>
      
      </body>
    </html>
  );
}
