import localFont from "next/font/local";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { ThemeProvider } from "next-themes";

const vaz = localFont({
  src: "../app/fonts/Vazir-FD.woff2",
  display: "swap",

});
export const metadata = {
  title: "فرم نظرسنجی",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa-IR" dir="rtl" suppressHydrationWarning>
      <body
        className={`h-screen w-screen  dynamic-padding test overflow-auto 
           bg-black text-blue-500
           text-small
            xl:text-amber-300 xl:text-3xl 
             2xl:text-purple-500 2xl:text-7xl 
             md:text-2xl
              md:text-red-600
               ${vaz.className} antialiased`}
      >
        <ThemeProvider >
      <NextUIProvider>  {children} </NextUIProvider>

        </ThemeProvider>
      
      </body>
    </html>
  );
}
