import localFont from "next/font/local";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { ThemeProvider } from "next-themes";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa-IR" dir="rtl" suppressHydrationWarning>
      <body
        className={`h-screen w-screen  bg-black text-blue-500 xl:text-amber-300 2xl:text-purple-500 2xl:text-8xl xl:text-6xl md:text-3xl md:text-red-600 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider >
      <NextUIProvider>  {children} </NextUIProvider>

        </ThemeProvider>
      
      </body>
    </html>
  );
}
